name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.semrel.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Semantic release
        id: semrel
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  binaries:
    name: Binaries ${{ matrix.goos }}/${{ matrix.goarch }}
    needs: release
    if: needs.release.outputs.version != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and upload
        uses: wangyoucao577/go-release-action@279495102627de7960cbc33434ab01a12bae144b # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: go.mod
          ldflags: -s -w
          pre_command: export CGO_ENABLED=0
          binary_name: vantrue-gpx
          release_tag: v${{ needs.release.outputs.version }}
          overwrite: true
          compress_assets: OFF
          md5sum: "FALSE"
          sha256sum: "TRUE"
          asset_name: vantrue-gpx-${{ matrix.goos }}-${{ matrix.goarch }}
